apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.name }}
spec:
  selector:
      name: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-slave
  namespace: {{ .Values.name }}
spec:
  selector:
      name: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portForSlave }}
      targetPort: {{ .Values.service.portForSlave }}
      nodePort: {{ .Values.service.nodePortForSlave }}