// To connect localhost to git for hook run: "ssh -R 80:localhost:8080 ssh.localhost.run" and copy output URL to git hook

properties([
githubProjectProperty(displayName: '', projectUrlStr: 'https://github.com/shaharco99/Devops/'),
parameters([
    choice(choices: ['apply', 'destroy'], name: 'action'),
    choice(choices: ['eu-central-1', 'us-east-2', 'us-east-1', 'us-west-1', 'us-west-2', 'af-south-1', 'ap-east-1', 'ap-southeast-3', 'ap-south-1', 'ap-northeast-3', 'ap-northeast-2', 'ap-southeast-1', 'ap-southeast-2', 'ap-northeast-1', 'ca-central-1', 'eu-west-1', 'eu-west-2', 'eu-south-1', 'eu-west-3', 'eu-north-1', 'me-south-1', 'me-central-1', 'sa-east-1'], description: 'use "eu-central-1" as default', name: 'region'),
    string(defaultValue: '1', description: 'change to amount of instances', name: 'amount_of_instance', trim: true)]),
pipelineTriggers([githubPush()])])
pipeline {
   agent any

//     uncomment if tunel is not config
// // Every hour ( perhaps at minutes :04, :14, :24 between 0-30)
//     triggers {
//       pollSCM '''TZ=Israel
//     H(0-30) * * * *'''
//    }

   tools {
      terraform 'Terraform'
      }


   environment {
       AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
       AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
   }

    stages {
        stage ('terraform init') {
        // TODO do only when init is required
              steps {
                dir('/home/shahar/Desktop/Devops/terraform-EC2') {
                    sh ('terraform init')
                }
            }
        }
        stage ('terraform Action') {
            steps {
                dir('/home/shahar/Desktop/Devops/terraform-EC2')
                {
                    sh ('terraform ${action} -auto-approve -var "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" -var "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" -var "amount_of_instance=${amount_of_instance}" -var "region=${region}"')
                }
            }
        }
    }
}